### ISSUE TITLE
Where to get train_dense_crf_cap.json?

### ISSUE THREAD

**Issue by C0desoda** [HKUST-KnowComp/VD-PCR#3]
Hello, how can I get train_dense_crf_cap.json?

**Comment by YuCosine** [comment]
Hi, before running the inference of Phase 2, preprocess the data with:
```
python preprocessing/extract_relevant_history.py --include_cap --save_name crf_cap
```

I have add this line into "Direct inference" - "Phase 2" in README. Thanks for pointing out this out.
