### ISSUE TITLE
question about config

### ISSUE THREAD

**Issue by lclszsdnr** [HKUST-KnowComp/VD-PCR#5]
Hello,When I was studying the code of your thesis, some config parameters were not very clear, and I couldn’t find them in config/readme. Is there any contact information that I can ask you for advice？thanks！

**Comment by YuCosine** [comment]
Hi, you can directly post your question here and I will get notification by github to answer it.

**Comment by lclszsdnr** [comment]
Thank you very much for your reply. My question is a little bit more. I have studied your related articles and would like to ask some questions about visual reference resolution. If possible, can you add QQ 354793567, I promise I will only ask you a few academic questions and code questions, thank you very much!

**Comment by YuCosine** [comment]
I do not use QQ. You can email me at yucosine@163.com.
